baseURL = "https://learn.cspratik.com/"
languageCode = 'en-us'
title = 'Learning Center - CS Pratik K Shah'
contentDir= "content"
theme = "lotusdocs"
relativeURLs = true
canonifyURLs = true

[module]
  [[module.imports]]
    path = "github.com/colinwilson/lotusdocs"
    disable = true