[build]
  publish = "public"
  hugo --gc --minify --baseURL $DEPLOY_PRIME_URL
  
[build.environment]
  HUGO_VERSION = "0.148.2"  # Replace with your local Hugo version (run `hugo version`)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"