[build]
  publish = "public"
  hugo --minify
  
[build.environment]
  HUGO_VERSION = "0.148.2"  # Replace with your local Hugo version (run `hugo version`)
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"