[build]
  publish = "public/docs"
  command = "hugo --gc --minify"
[build.environment]
  HUGO_VERSION = "0.148.2"  # Replace with your local Hugo version (run `hugo version`)

[[redirects]]
  from = "/css/*"
  to = "/docs/css/:splat"
  status = 200
[[redirects]]
  from = "/js/*"
  to = "/docs/js/:splat"
  status = 200
[[redirects]]
  from = "/images/*"
  to = "/docs/images/:splat"
  status = 200
[[redirects]]
  from = "/site.webmanifest"
  to = "/docs/site.webmanifest"
  status = 200
[[headers]]
  for = "/site.webmanifest"
  [headers.values]
    Access-Control-Allow-Origin = "https://learn.cspratik.com"